import { NextResponse } from 'next/server';
import connectToDatabase from '@/lib/mongodb';
import User from '@/models/User';

export const maxDuration = 300; // Allow 5 minutes for complex cross-client processing

export async function POST(req: Request) {
  try {
    // 1. Authenticate the incoming Jules Webhook
    const url = new URL(req.url);
    const authHeader = req.headers.get('Authorization') || '';
    const queryKey = url.searchParams.get('key') || url.searchParams.get('secret') || url.searchParams.get('token') || '';
    const providedKey = authHeader.replace('Bearer ', '').trim() || queryKey.trim();

    if (!providedKey || providedKey !== process.env.JULES_API_KEY) {
       console.warn(`[JULES WEBHOOK] Unauthorized access attempt detected with key sequence: ${providedKey.substring(0, 5)}...`);
       return NextResponse.json({ error: 'Unauthorized Autonomous Trigger' }, { status: 401 });
    }

    await connectToDatabase();
    
    // 2. Fetch all clients who have enabled SEO Autopilot
    const activeClients = await User.find({ seoAutomation: true });
    
    if (activeClients.length === 0) {
      return NextResponse.json({ success: true, message: 'Jules found no active autopilot pipelines.' });
    }

    let clientsProcessed = 0;
    let totalDripCount = 0;
    let totalPrepCount = 0;

    // 3. Process Jules Queue for Each active Client
    for (const client of activeClients) {
        let clusters = client.seoClusters || [];
        
        // -------------------------------------------------------------
        // PHASE 1: JULES DRIP PIPELINE (EAT DRAFTS -> LIVE)
        // -------------------------------------------------------------
        const readyForLive = clusters.filter((c: any) => 
            ['draft', 'queued'].includes(c.status) && 
            (c.htmlContent && c.htmlContent !== 'AUTOGENERATED' || c.heroImage)
        );
        
        // Jules organically eats at the specified User velocity limit to optimize Google's Crawl Budget.
        const dripLimit = client.dailyPageProductionLimit || 5; 
        const toDrip = readyForLive.slice(0, dripLimit);
        
        for (const node of toDrip) {
             const idx = clusters.findIndex((c: any) => c._id === node._id);
             if (idx > -1) {
                 clusters[idx].status = 'Live';
                 clusters[idx].pushedAt = new Date();
                 totalDripCount++;
             }
        }
        
        // -------------------------------------------------------------
        // PHASE 2: JULES PREP PIPELINE (IDEA -> DRAFT)
        // -------------------------------------------------------------
        const rawIdeas = clusters.filter((c: any) => ['idea', 'queued'].includes(c.status) && !c.htmlContent);
        
        // Limit prep to explicitly match the domain's custom velocity budget
        const toPrep = rawIdeas.slice(0, client.dailyPageProductionLimit || 5);
        
        if (toPrep.length > 0) {
            const jwt = require('jsonwebtoken');
            const tempToken = jwt.sign({ role: 'superadmin' }, process.env.JWT_SECRET || 'fallback-secret-for-local-dev');
            const host = req.headers.get('host');
            const protocol = process.env.NODE_ENV === 'development' ? 'http' : 'https';
            const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || `${protocol}://${host}`;
            
            const internalHeaders = {
               'Content-Type': 'application/json',
               'Cookie': `admin_token=${tempToken}`
            };

            for (const idea of toPrep) {
                 const idx = clusters.findIndex((c: any) => c._id === idea._id);
                 if (idx > -1) {
                     console.log(`[JULES PREP] Triggering Replicate Media Synthesis for ${idea.keyword}`);
                     // Generate High-Fidelity Images
                     await fetch(`${baseUrl}/api/admin/seo/generate-media`, {
                         method: 'POST',
                         headers: internalHeaders,
                         body: JSON.stringify({ userId: client._id, clusterId: idea._id, keyword: idea.keyword })
                     });

                     console.log(`[JULES PREP] Triggering Gemini 3.1 Pro UI Layout Synthesis for ${idea.keyword}`);
                     // Generate Advanced Semantic HTML mapping Native Components
                     await fetch(`${baseUrl}/api/admin/seo/generate-content`, {
                         method: 'POST',
                         headers: internalHeaders,
                         body: JSON.stringify({ userId: client._id, clusterId: idea._id, keyword: idea.keyword, isLlmQA: false })
                     });
                     
                     // Finally, visually move it into the Sandbox for manual client verify
                     clusters[idx].status = 'draft'; 
                     totalPrepCount++;
                 }
            }
        }
        
        // Ensure updates are saved
        client.seoClusters = clusters;
        await client.save();
        clientsProcessed++;
    }

    console.log(`[JULES WEBHOOK] Successfully processed ${clientsProcessed} clients. Dripped ${totalDripCount} to Live. Prepped ${totalPrepCount} to Draft.`);

    return NextResponse.json({ 
        success: true, 
        message: 'Jules Autonomous Drip Matrix Executed Successfully via Webhook', 
        metrics: {
            clientsProcessed,
            pagesDrippedToLive: totalDripCount,
            pagesPreppedToDraft: totalPrepCount
        }
    });
    
  } catch (error: any) {
    console.error("[JULES CRON FATAL ERROR]", error);
    return NextResponse.json({ error: `Autonomous Engine Failure: ${error.message}` }, { status: 500 });
  }
}

export async function GET(req: Request) {
    return POST(req);
}
