/**
 * models/SeoPolicyProposal.ts
 *
 * Candidate policy change generated by the evolution cycle.
 * Must pass shouldPromotePolicyProposal (10+ samples, positive evidence)
 * before being applied to the live evolution state.
 */

import { Schema, model, models } from 'mongoose';

const SeoPolicyProposalSchema = new Schema({
  stateId:      { type: Schema.Types.ObjectId, ref: 'SeoPolicyEvolutionState', required: true, index: true },
  scopeType:    { type: String, enum: ['global','campaign','user'], required: true, index: true },
  scopeId:      { type: String, required: true, index: true },
  policyType:   { type: String, enum: ['optimizer','bandit','confidence_gate','budget_allocator'], required: true, index: true },

  currentVersion:  { type: Number, required: true },
  proposedVersion: { type: Number, required: true },

  // Dot-path keyed changes: e.g. { 'parameters.epsilon': 0.12 }
  changes:   { type: Schema.Types.Mixed, default: {} },
  rationale: { type: String, default: '' },

  evidence: {
    recentRewardDelta:      { type: Number, default: 0 },
    recentAccuracyDelta:    { type: Number, default: 0 },
    recentAttributionDelta: { type: Number, default: 0 },
    sampleCount:            { type: Number, default: 0 },
  },

  // Phase guard: only bandit + optimizer proposals can auto-promote
  autoPromoteEligible: { type: Boolean, default: false },

  status: { type: String, enum: ['proposed','approved','rejected','promoted'], default: 'proposed', index: true },
}, { timestamps: true });

SeoPolicyProposalSchema.index({ status: 1, createdAt: -1 });
SeoPolicyProposalSchema.index({ policyType: 1, status: 1, createdAt: -1 });

export default models.SeoPolicyProposal || model('SeoPolicyProposal', SeoPolicyProposalSchema);
